### ISSUE TITLE
Get ECG data in ezcgp

### ISSUE THREAD

**Issue by anishthite** [ezCGP/ezCGP#267]

**Comment by gabriel-q-wang** [comment]
Don't push data to the repo or I will cry

**Comment by roddtalebi** [comment]
lol me too!
if you don't have time to write a whole shell script to download the data, at least make a text file with instructions on how to download the data and put it here
https://github.com/ezCGP/ezCGP/tree/master/data/download_data/linux

**Comment by anishthite** [comment]
Oh lol I was just going to subclass the simgan data class and reference the files, cause right now the simgan data class generates everything in it.

**Comment by gabriel-q-wang** [comment]
Oh then check out the ecg branch of the SimGAN repo, I think I had a made an ecg dataset class. Don't remember what else I chenged in that branch but it should plug and play with the dataset I gave you.

Sorry I have ptsd from the vip when people would commit anything and everything

**Comment by gabriel-q-wang** [comment]
Box link for the dataset: https://gtri.box.com/s/galrwlvcqb2kodxuq5tcfi6wwoty1g0n

Grab abnormal.npy and sim_dataset.npy

**Comment by roddtalebi** [comment]
Sorry to be a bummer, but if I just realized that if we're going to tag the ecg code, we need to make the data available. Can you send a link to the source or drop code on how you made those npy files? I can clean it up and put it on github or part of the release note on my own time

**Comment by gabriel-q-wang** [comment]
Yeah I’ve got some jupyter notebooks that handle the downloading, reading, and splitting the data. We also have some new standalone scripts for the ECG classifiers as well as some updated signal graphing code. Do you have a preference as to where we should put them?

**Comment by roddtalebi** [comment]
https://github.com/ezCGP/ezCGP/tree/SimGAN-supplements/misc/simgan_supplements

**Comment by roddtalebi** [comment]
just dump in there and then give a sentence or two overview on this issue as to what i need to know to save me the time from reading code and working backwards

**Comment by gabriel-q-wang** [comment]
Finally got around to this. So I just pushed up three files.

1) gen_ecg_sim.ipynb is a jupyter notebook that uses the neurokit2 python package to generate the simulated dataset and visualizes some examples, runs right out of the box. Produces sim_dataset.npy

2) read_mit_bih.ipynb is a jupyter notebook that reads in the original files from MIT-BIH and converts it to numpy and splits it into training sets. The link for the original data and instructions are included in the comments of the notebook. The notebook visualizes the classes and the imbalance between them. I played around with splitting it up into multiple classes based on the original MIT-BIH annotations but for the GECCO paper we focused on binary classification. Produces normal.npy and abnormal.npy

3) ecg_train_classfier.py is a python script meant to be run after an ezCGP SimGAN run that trains binary classifiers to compare what happens when we train them on only real data, real + simulated, and real + refined data, used to produce the table in the GECCO paper. It prints out the F1 scores, and saves the confusion matrices. Requires an individual's information from ezCGP so the pickle file and the folder.
