### ISSUE TITLE
Load Pretrained Pytorch Models offline

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#268]
Good resource:
https://www.codetd.com/en/article/12814441

...from the webpage:

The download addresses of various vgg models are indicated in model_urls. The specific download method is to directly copy the URL and open it, such as vgg16. Copy the URL https://download.pytorch.org/models/vgg16-397923af.pth and open it in the browser. It will automatically open the download interface for downloading. After the download is complete, place it in the folder you are currently running. The loaded program needs to be modified, as follows:

```
model = models.vgg16(pretrained=False)
pre = torch.load('vgg16-397923af.pth')
model.load_state_dict(pre)
```

**Comment by roddtalebi** [comment]
it might not actually be a pretrained pytorch model but some other pytorch thing...

I recommend making a new conda env, disconnecting from wifi, and run simgan to see if we can mimic problems from the room

**Comment by roddtalebi** [comment]
followed my earlier suggestion, saw this print statement:
```
Using cache found in /home/roddtalebi/.cache/torch/hub/pytorch_vision_v0.8.0
```

Deleted that folder and reran to see this statemenet:
```
Downloading: "https://github.com/pytorch/vision/archive/v0.8.0.zip" to /home/roddtalebi/.cache/torch/hub/v0.8.0.zip
```

Wifi turned off, it errors on
```
File "/home/roddtalebi/Documents/ezCGP/codes/utilities/simgan_fid_metric.py", line 13, in <module>
    model = torch.hub.load('pytorch/vision:v0.8.0', 'inception_v3', pretrained=True)
```

Bingo!

**Comment by gabriel-q-wang** [comment]
Not sure if this applies to this issue, but just got this error while fixing local loss:

RuntimeError: Deterministic behavior was enabled with either torch.set_deterministic(True) or at::Context::setDeterministic(true), but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility

GPU reproducibility is a pain.

**Comment by roddtalebi** [comment]
It looks like if we are using old versions of torch/torchvision, we have to use the inception model from that version...

like here is the one used in torchvision 0.4.2 (see Issue #274)
https://github.com/pytorch/vision/blob/v0.4.2/torchvision/models/inception.py#L13

or else the way the .pth files are compressed get different at somepoint...not ideal

**Comment by roddtalebi** [comment]
up to 0.9 they use "inception_v3_google-1a9a5a14.pth"
0.10 and up -> "inception_v3_google-0cc3c7bd.pth"
